export type CartItem = { productId: string; variantId?: string; name: string; size?: string; price: number; image?: string; quantity: number; stock?: number };
export type CartAddedDetail = { item: CartItem; quantityAdded: number; items: CartItem[] };
const CART_KEY = 'boozepap-cart-v2', LEGACY_CART_KEY = 'chupahub-cart', CART_VERSION_KEY = 'boozepap-cart-version';
const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function validItems(value: unknown): CartItem[] { if (!Array.isArray(value)) return []; return value.filter((item): item is CartItem => Boolean(item && typeof item === 'object' && uuid.test(String((item as CartItem).productId || '')) && Number.isInteger(Number((item as CartItem).quantity)) && Number((item as CartItem).quantity) > 0)); }
export function readCart(): CartItem[] { try { if (localStorage.getItem(CART_VERSION_KEY) !== '2') { const migrated = validItems(JSON.parse(localStorage.getItem(LEGACY_CART_KEY) || '[]')); localStorage.setItem(CART_KEY, JSON.stringify(migrated)); localStorage.removeItem(LEGACY_CART_KEY); localStorage.setItem(CART_VERSION_KEY, '2'); return migrated; } return validItems(JSON.parse(localStorage.getItem(CART_KEY) || '[]')); } catch { return []; } }
export function writeCart(items: CartItem[], added?: Omit<CartAddedDetail, 'items'>) { const next = validItems(items.filter((item) => item.quantity > 0)); localStorage.setItem(CART_KEY, JSON.stringify(next)); localStorage.setItem(CART_VERSION_KEY, '2'); window.dispatchEvent(added ? new CustomEvent<CartAddedDetail>('chupahub-cart-updated', { detail: { ...added, items: next } }) : new Event('chupahub-cart-updated')); }
export function updateCartQuantity(productId: string, variantId: string | undefined, quantity: number) { const items = readCart(); const index = items.findIndex((item) => item.productId === productId && item.variantId === variantId); if (index >= 0) { if (quantity <= 0) items.splice(index, 1); else items[index].quantity = Math.min(quantity, items[index].stock ?? quantity); writeCart(items); } }
export function removeUnavailableCartProducts(ids: string[]) { const missing = new Set(ids); writeCart(readCart().filter(item => !missing.has(item.productId))); }
